In [2]:
import numpy as np

In [3]:
import pandas as pd

In [4]:
data = [
    ['Nissan', 'Stanza', 1991, 138, 4, 'MANUAL', 'sedan', 2000],
    ['Hyundai', 'Sonata', 2017, None, 4, 'AUTOMATIC', 'Sedan', 27150],
    ['Lotus', 'Elise', 2010, 218, 4, 'MANUAL', 'convertible', 54990],
    ['GMC', 'Acadia',  2017, 194, 4, 'AUTOMATIC', '4dr SUV', 34450],
    ['Nissan', 'Frontier', 2017, 261, 6, 'MANUAL', 'Pickup', 32340],
]

columns = [
    'Make', 'Model', 'Year', 'Engine HP', 'Engine Cylinders',
    'Transmission Type', 'Vehicle_Style', 'MSRP'
]

In [5]:
df = pd.DataFrame(data, columns=columns)

In [6]:
df

,Make,Model,Year,Engine HP,Engine Cylinders,Transmission Type,Vehicle_Style,MSRP
0,Nissan,Stanza,1991,138.0,4,MANUAL,sedan,2000
1,Hyundai,Sonata,2017,NaN,4,AUTOMATIC,Sedan,27150
2,Lotus,Elise,2010,218.0,4,MANUAL,convertible,54990
3,GMC,Acadia,2017,194.0,4,AUTOMATIC,4dr SUV,34450
4,Nissan,Frontier,2017,261.0,6,MANUAL,Pickup,32340

In [7]:
data = [
    {
        "Make": "Nissan",
        "Model": "Stanza",
        "Year": 1991,
        "Engine HP": 138.0,
        "Engine Cylinders": 4,
        "Transmission Type": "MANUAL",
        "Vehicle_Style": "sedan",
        "MSRP": 2000
    },
    {
        "Make": "Hyundai",
        "Model": "Sonata",
        "Year": 2017,
        "Engine HP": None,
        "Engine Cylinders": 4,
        "Transmission Type": "AUTOMATIC",
        "Vehicle_Style": "Sedan",
        "MSRP": 27150
    },
    # ...
]

In [9]:
df = pd.DataFrame(data)

In [10]:
df

,Make,Model,Year,Engine HP,Engine Cylinders,Transmission Type,Vehicle_Style,MSRP
0,Nissan,Stanza,1991,138.0,4,MANUAL,sedan,2000
1,Hyundai,Sonata,2017,NaN,4,AUTOMATIC,Sedan,27150

In [11]:
df.head(n=2)

,Make,Model,Year,Engine HP,Engine Cylinders,Transmission Type,Vehicle_Style,MSRP
0,Nissan,Stanza,1991,138.0,4,MANUAL,sedan,2000
1,Hyundai,Sonata,2017,NaN,4,AUTOMATIC,Sedan,27150

In [12]:
df.Make

0     Nissan
1    Hyundai
Name: Make, dtype: str

In [13]:
df['Engine HP']

0    138.0
1      NaN
Name: Engine HP, dtype: float64

In [14]:
df[['Make', 'Model', 'MSRP']]

      Make   Model   MSRP
0   Nissan  Stanza   2000
1  Hyundai  Sonata  27150

In [16]:
df['id'] = [1, 2]

In [17]:
df

,Make,Model,Year,Engine HP,Engine Cylinders,Transmission Type,Vehicle_Style,MSRP,id
0,Nissan,Stanza,1991,138.0,4,MANUAL,sedan,2000,1
1,Hyundai,Sonata,2017,NaN,4,AUTOMATIC,Sedan,27150,2

In [18]:
del df['id']

In [19]:
df

,Make,Model,Year,Engine HP,Engine Cylinders,Transmission Type,Vehicle_Style,MSRP
0,Nissan,Stanza,1991,138.0,4,MANUAL,sedan,2000
1,Hyundai,Sonata,2017,NaN,4,AUTOMATIC,Sedan,27150

In [20]:
df.loc[1]

Make                   Hyundai
Model                   Sonata
Year                      2017
Engine HP                  NaN
Engine Cylinders             4
Transmission Type    AUTOMATIC
Vehicle_Style            Sedan
MSRP                     27150
Name: 1, dtype: object

In [22]:
df.index = ['a', 'b']

In [23]:
df.iloc[[1]]

,Make,Model,Year,Engine HP,Engine Cylinders,Transmission Type,Vehicle_Style,MSRP
b,Hyundai,Sonata,2017,NaN,4,AUTOMATIC,Sedan,27150

In [28]:
df.loc["b"]

Make                   Hyundai
Model                   Sonata
Year                      2017
Engine HP                  NaN
Engine Cylinders             4
Transmission Type    AUTOMATIC
Vehicle_Style            Sedan
MSRP                     27150
Name: b, dtype: object

In [30]:
df = df.reset_index(drop=True)

In [31]:
df

,Make,Model,Year,Engine HP,Engine Cylinders,Transmission Type,Vehicle_Style,MSRP
0,Nissan,Stanza,1991,138.0,4,MANUAL,sedan,2000
1,Hyundai,Sonata,2017,NaN,4,AUTOMATIC,Sedan,27150

In [32]:
df['Engine HP'] * 2

0    276.0
1      NaN
Name: Engine HP, dtype: float64

In [33]:
df['Year'] >= 2015

0    False
1     True
Name: Year, dtype: bool

In [34]:
df['Year'] >= 2015

0    False
1     True
Name: Year, dtype: bool

In [35]:
>>> df[
...     df['Year'] >= 2015
... ]

,Make,Model,Year,Engine HP,Engine Cylinders,Transmission Type,Vehicle_Style,MSRP
1,Hyundai,Sonata,2017,NaN,4,AUTOMATIC,Sedan,27150

In [36]:
>>> df[
...     df['Make'] == 'Nissan'
... ]

,Make,Model,Year,Engine HP,Engine Cylinders,Transmission Type,Vehicle_Style,MSRP
0,Nissan,Stanza,1991,138.0,4,MANUAL,sedan,2000

In [38]:
>>> df[
...     (df['Make'] == 'Nissan') & (df['Year'] >= 1990)
... ]

,Make,Model,Year,Engine HP,Engine Cylinders,Transmission Type,Vehicle_Style,MSRP
0,Nissan,Stanza,1991,138.0,4,MANUAL,sedan,2000

In [39]:
df['Vehicle_Style'].str.lower()

0    sedan
1    sedan
Name: Vehicle_Style, dtype: str

In [40]:
'machine learning zoomcamp'.replace(' ', '_')

'machine_learning_zoomcamp'

In [41]:
>>> df['Vehicle_Style'].str.replace(' ', '_')

0    sedan
1    Sedan
Name: Vehicle_Style, dtype: str

In [42]:
>>> df['Vehicle_Style'].str.replace('S', 's')

0    sedan
1    sedan
Name: Vehicle_Style, dtype: str

In [43]:
df.MSRP.describe()

count        2.000000
mean     14575.000000
std      17783.735547
min       2000.000000
25%       8287.500000
50%      14575.000000
75%      20862.500000
max      27150.000000
Name: MSRP, dtype: float64

In [44]:
df.describe().round(2)

          Year  Engine HP  Engine Cylinders      MSRP
count     2.00        1.0               2.0      2.00
mean   2004.00      138.0               4.0  14575.00
std      18.38        NaN               0.0  17783.74
min    1991.00      138.0               4.0   2000.00
25%    1997.50      138.0               4.0   8287.50
50%    2004.00      138.0               4.0  14575.00
75%    2010.50      138.0               4.0  20862.50
max    2017.00      138.0               4.0  27150.00

In [45]:
df.Make.nunique()

2

In [46]:
df.isnull().sum()

Make                 0
Model                0
Year                 0
Engine HP            1
Engine Cylinders     0
Transmission Type    0
Vehicle_Style        0
MSRP                 0
dtype: int64

In [48]:
df.groupby('Transmission Type').MSRP.mean()

Transmission Type
AUTOMATIC    27150.0
MANUAL        2000.0
Name: MSRP, dtype: float64

In [49]:
df.to_dict(orient='records')

[{'Make': 'Nissan',
  'Model': 'Stanza',
  'Year': 1991,
  'Engine HP': 138.0,
  'Engine Cylinders': 4,
  'Transmission Type': 'MANUAL',
  'Vehicle_Style': 'sedan',
  'MSRP': 2000},
 {'Make': 'Hyundai',
  'Model': 'Sonata',
  'Year': 2017,
  'Engine HP': nan,
  'Engine Cylinders': 4,
  'Transmission Type': 'AUTOMATIC',
  'Vehicle_Style': 'Sedan',
  'MSRP': 27150}]